### ISSUE TITLE
Unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by lightmed** [op-developer/psd2-registration-example#8]
I got this when program tries to register (https://mtls-apis.psd2-sandbox.op.fi/tpp-registration/register): PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target. 

I'm not a Java expert, but seems that program uses it's own TrustStore, so I don't have to add certificate to anywhere (although I tried that too)?

**Comment by keksipurkki** [comment]
Thanks for the bug report. We noticed an issue with the QWAC and will report here once the issue has been resolved. 

Elias T. / PSD2 at OP Financial Group

**Comment by keksipurkki** [comment]
The QWAC issues should be resolved in sandbox. @lightmed Can you verify that you do not get the TLS alert anymore?

**Comment by lightmed** [comment]
It's working, thank you!
